name: "dbt_ecommerce"
version: "1.0.0"
config-version: 2

profile: "dbt_ecommerce"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbt_ecommerce:
    +schema: raw
    +enabled: true
    # No special configuration for problematic files

models:
  dbt_ecommerce:
    staging:
      +schema: staging
    validation:
      +schema: validation
